# Generated by Django 5.1 on 2024-08-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0002_remove_book_author_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(blank=True, related_name='author', to='libraryApp.author'),
        ),
    ]
