# Generated by Django 5.1 on 2024-08-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0003_alter_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='location',
        ),
        migrations.AddField(
            model_name='author',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='city'),
        ),
    ]
